version: '2.1'
orbs:
  node: circleci/node@7.2.0
jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '24.9.0'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y libnspr4 
          npm install selenium-webdriver
          node test.js

workflows:
  test_my_app:
    jobs:
      - install-node-example